source ~/.profile

COLOR1="\[\033[0;36m\]" # Cyan
COLOR2="\[\033[0;32m\]" # Light Green
COLOR3="\[\033[0;36m\]" # Cyan
COLOR4="\[\033[0;31m\]" # Red
COLOR5="\[\033[0m\]"    # White

export PS1="$COLOR1\u$COLOR2\h$COLOR1\w$COLOR4 :: $COLOR5"

# Bash completion
if [ -z "$BASH_COMPLETION" ] && [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

unset HISTFILE
export HISTCONTROL=ignoreboth

if [ -f $HOME/.bashrc.local ]; then
    . $HOME/.bashrc.local
fi
