#!/bin/sh

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export FZF_DEFAULT_OPTS="--multi"

export EDITOR=vim
export VISUAL=vim

export NAME='Tom Fitzhenry'
export EMAIL='tom@tom-fitzhenry.me.uk'

if [ -f ~/.environment.local ]; then
    . ~/.environment.local
fi
