#!/bin/sh

export GOROOT=$HOME/opt/go/

export PATH=$HOME/bin:$GOROOT/bin:$PATH
export LANG=en_GB.utf-8

export BROWSER=/usr/bin/chromium-browser
export EDITOR=vim
export VISUAL=vim

export NAME='Tom Fitzhenry'
export EMAIL='tom@tom-fitzhenry.me.uk'
export DEBEMAIL=$EMAIL
export DEBFULLNAME="$NAME"
export GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt

export GOPATH=$HOME/src/go/

if [ -f ~/.environment.local ]; then
    . ~/.environment.local
fi
