#!/bin/sh

export PATH=$HOME/bin:$HOME/usr/bin/:$HOME/usr/local/bin/:/var/lib/gems/1.8/bin:/usr/lib/postgresql/8.3/bin:$PATH:/opt/WorldOfGoo/
export PATH=$HOME/.cabal/bin/:$PATH
export PATH=$PATH:/usr/local/share/npm/bin/
export LANG=en_GB.utf-8

export BROWSER=/usr/bin/chromium-browser
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

export NNTPSERVER=news.virginmedia.com
export NNTPSERVER=news.gmane.org

# Stops 'less' from writing to '~/.lesshst"
export LESSHISTFILE="-"

export GREP_OPTIONS='--color=auto'

# On systems that supported ipv6, some mpd clients wouldn't work
# because they look at 'localhost' by default and they looked for
# ipv6 localhost. Explicately putting 127.0.0.1 (i.e. ipv4 localhost)
# worked. MPD runs on ipv4 localhost.
export MPD_HOST=127.0.0.1

export NAME='Tom Fitzhenry'
export EMAIL='tom@tom-fitzhenry.me.uk'
export DEBEMAIL=$EMAIL
export DEBFULLNAME="$NAME"
export GIT_AUTHOR_NAME="$NAME"
export GIT_AUTHOR_EMAIL=$EMAIL
export GIT_COMMITTER_NAME="$NAME"
export GIT_COMMITTER_EMAIL=$EMAIL

. ~/.config/user-dirs.dirs
export MUSIC_STORE_DIR="/files/public/music/"

export GOPATH=$HOME/src/go

if [ -f ~/.environment.local ]; then
    . ~/.environment.local
fi
export URBIT_HOME=/home/tom/tmp/urbit.oZg8RF/urbit/urb
