set -g prefix C-a
bind C-A send-prefix

bind C-a last-window

# tmux adds a very small delay when sending commands, and this delay can interfere with other programs such as the Vim text editor. We can set this delay so it’s much more responsive. -- tmux book
set -sg escape-time 1

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind | split-window -h
bind - split-window -v

# Maximise/minimise a pane
# http://superuser.com/questions/238702/maximizing-a-pane-in-tmux#comment467259_357799
bind M new-window -d -n tmux-zoom \; swap-pane -s tmux-zoom.0 \; select-window -t tmux-zoom
bind m last-window \; swap-pane -s tmux-zoom.0 \; kill-window -t tmux-zoom

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r K confirm-before -p "kill-pane #P? (y/n)" kill-pane

set-option -g lock-command vlock
bind x lock-session

setw -g mode-mouse off


set -g status-fg white
set -g status-bg black

setw -g window-status-fg cyan
setw -g window-status-bg default
setw -g window-status-attr dim

setw -g window-status-current-fg white
setw -g window-status-current-bg red
setw -g window-status-current-attr bright

set -g pane-border-fg green
set -g pane-border-bg black
set -g pane-active-border-fg white
set -g pane-active-border-bg yellow

set -g message-fg white
set -g message-bg black
set -g message-attr bright

set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P"
set -g status-right "#[fg=cyan]%Y-%m-%d %H:%M"
set -g status-utf8 on
set -g status-interval 60
set -g status-justify centre
setw -g monitor-activity on
set -g visual-activity on
