set -g prefix C-a

set -g renumber-windows on

set -g status-fg white
set -g status-bg black

setw -g window-status-format '#W'
setw -g window-status-current-format '#W'
setw -g window-status-current-attr bright

set -g status-right ""

setw -g monitor-activity on

run-shell ~/.tmux/plugins/tmux-sensible/sensible.tmux
run-shell ~/.tmux/plugins/tmux-pain-control/pain_control.tmux
run-shell ~/.tmux/plugins/tmux-fpp/fpp.tmux
