" ~/.vimrc
" Configuration put together by Tim Monks, after reading a few other .rcs ^_^

" Use Vim extensions and fix screen issues "
""""""""""""""""""""""""""""""""""""""""""""
set nocompatible "compatible mode == emulate vi's problems
if &term =~ "screen"
	set term=xterm
endif
set history=50 "keep 50 lines of command line history
set autowrite " Automatically save before commands like :next and :make
set showcmd
set wildmenu " shows tab completion menu during a command
set backspace=2 "mean that you can always backspace

" Appearance "
""""""""""""""
set nu " line numbers
colorscheme elflord
if has("syntax")
	syntax on
endif
filetype indent on
set showcmd
set listchars=tab:`\ ,trail:.
set list "list mode displays all your special characters, define them above
set linebreak
set showbreak=>>

" Highlight merge markers
highlight MergeMarker guibg=red ctermbg=red
match MergeMarker /^[<=>]\{7\}.*$/

" Indentation "
"""""""""""""""
set tabstop=4
set st=4
set shiftwidth=4 "when using << and >> to indent, this value is used
set autoindent
set smartindent "can't remember whether you need both of these. I think yes. :)

" Stuff that was in my vimrc, whose purpose I can't remember "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin on
filetype on
set modeline
set expandtab
set smarttab
set softtabstop=4

for f in split(glob('~/.vim/rc/*.vim'), '\n')
    exe 'source' f
endfor
