# Put /usr/local/bin (Homebrew) before /usr/bin
# I could modify /etc/paths to put /usr/local/bin before /usr/bin
# but that might screw over system processes.
export PATH=/usr/local/bin:$PATH

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export EDITOR=vim
export VISUAL=vim

export NAME='Tom Fitzhenry'
export EMAIL='tom@tom-fitzhenry.me.uk'

if [ -f ~/.environment.local ]; then
    . ~/.environment.local
fi
