zstyle :compinstall filename ~/.zshrc

source ~/.profile

# Set the keybindings to emacs bindings, so when I press "Up", the cursor
# is positioned at the end of the previous line, rather than the start of the
# previous line. There's probably a less draonic solution, involving rebinding
# "Up", but this solution will do.
# http://www.zshwiki.org/home/zle/bindkeys
# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=383737 (?)
bindkey -e

# Temporary fix for https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/621632
export TERM=linux

autoload colors && colors

setopt appendhistory autocd extendedglob nomatch notify interactivecomments

autoload -Uz compinit
compinit

unsetopt beep

alias -g 'L'='| less'

[ -f /etc/DIR_COLORS ] && eval $(dircolors -b /etc/DIR_COLORS)
export ZLSCOLORS="${LS_COLORS}"

if [ $UID -eq 0 ]; then
	PROMPT="%{$reset_color$fg_bold[red]%}%n@%B%m%b:%~%# "
else
	PROMPT="%{$fg_bold[blue]%}%n@%m%{$reset_color%}:%{$fg[red]%}%~%{$reset_color%}%# "
fi

if [ -f ~/.zshrc.local ]; then
    . ~/.zshrc.local
fi
