{ config, lib, ... }:
let
  inherit (builtins) attrNames;
  inherit (lib) concatMapStrings mkOption types;
  vars = config.home.sessionVariables;
in
{
  options = {
    home.sessionVariables = mkOption {
      type = types.attrsOf types.str;
      default = { };
      example = {
        EDITOR = "mg";
      };
      description = ''
        Environment variables to export in the user session, as
        `export VAR=value` lines in the generated `~/.bashrc`.
      '';
    };

    home.bashrc.extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra shell code appended to the generated `~/.bashrc`.";
    };
  };

  config.file.home.".bashrc".text = ''
    # Generated by nix-maid. Edit home.sessionVariables and home.bashrc.extraConfig instead.
    ${concatMapStrings (name: "export ${name}=\"${vars.${name}}\"\n") (attrNames vars)}
    ${config.home.bashrc.extraConfig}
  '';
}
