#!/bin/sh

set -eu

current_dir=$(pwd)

cd ~

cp -r \
  .bashrc .bash_profile .bash_logout .caffrc .certs/ .environment .gitconfig \
  .htoprc .mailcap .msmtprc .mutt/ .offlineimaprc \
  .procmailrc .reportbugrc  .screenrc  .signature .vimrc \
  .xbindkeysrc  .Xdefaults  .xinitrc \
  $current_dir

cd $current_dir
