#!/bin/sh
set -eu

PACKAGES="
ack-grep
apt-file
diffutils
dnsutils
elpa-async
elpa-bind-key
elpa-elfeed
elpa-evil
elpa-ledger
elpa-magit
elpa-projectile
elpa-use-package
git
htop
iotop
jq
magic-wormhole
moreutils
mosh
mpv
ncdu
netcat-traditional
pwgen
silversearcher-ag
socat
strace
sudo
tree
tmux
vim-nox
"

for p in $PACKAGES; do
	dpkg -s $p || apt install -y $p
done
