#!/bin/sh

set -eu

fail() {
    echo "****"
    echo "FAILURE: $1"
    echo "****"
    exit 1
}

Install_symlink() {
    local SOURCE="${1}"
    local TARGET_PREFIX="${2}"
    local TARGET="${TARGET_PREFIX}$(basename ${SOURCE})"

    if [ ! "$(readlink ${TARGET})" = "${SOURCE}" ]; then
	    ln -s -v "${SOURCE}" "${TARGET}"
    fi

}

Install_file() {
    local FILE="${1}"
    local TARGET_PREFIX="${2}"

    if [ -f "${FILE}" ]; then
        Install_regular_file "${FILE}" "${TARGET_PREFIX}"
    elif [ -d ${FILE} ]; then
        Install_directory ${FILE} ${TARGET_PREFIX}
    elif [ -h ${FILE} ]; then
        Install_symlink ${FILE} ${TARGET_PREFIX}
    else
        fail "Expected file or directory. Actual: ${FILE}"
    fi
}

Install_regular_file() {
    local SOURCE="${1}"
    local TARGET_PREFIX="${2}"
    local TARGET="${TARGET_PREFIX}$(basename "${SOURCE}")"

    if [ -e "${TARGET}" -a ! -h "${TARGET}" ]; then
        diff -Naur "${SOURCE}" "${TARGET}" || true
        printf "WARNING: ${TARGET} already exists. Overwrite (Y/n)? "
        read response
        if [ "${response}" = "y" -o "${response}" = "Y" -o "${response}" = "" ]; then
            cp ${TARGET} ${TARGET}-$(date +"%Y%m%dT%H%M%S")
            rm ${TARGET}
            Install_symlink ${SOURCE} ${TARGET_PREFIX}
        fi
    else
        Install_symlink "${SOURCE}" "${TARGET_PREFIX}"
    fi
}


Install_directory() {
    local SOURCE_DIRECTORY="${1}"
    local TARGET_PREFIX="${2}"
    local TARGET="${TARGET_PREFIX}$(basename ${SOURCE_DIRECTORY})"

    mkdir -p ${TARGET}
    
    for SOURCE in ${SOURCE_DIRECTORY}/*;
    do
        Install_file "${SOURCE_DIRECTORY}/$(basename "${SOURCE}")" ${TARGET}/
    done
}

git submodule update --init

for FILE in "$(pwd)"/dotfiles/*;
do
    Install_file ${FILE} ${HOME}/.
done

# Stop the remote control daemon, which is the thing that opens iTunes
# when play/pause is triggered.
# Frustratingly, play/pause is trigger when I take my magic headphones off,
# even if I'm listening to https://youtube.com which doesn't even listen to
# play/pause OSX events.
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
