#!/bin/sh
set -eu

PACKAGES="
ack
apt-file
diffutils
dnsutils
elpa-ag
elpa-async
elpa-bind-key
elpa-counsel
elpa-elfeed
elpa-evil
elpa-go-mode
elpa-ivy
elpa-ledger
elpa-magit
elpa-notmuch
elpa-projectile
elpa-swiper
elpa-use-package
elpa-weechat
elpa-which-key
emms
git
htop
iotop
jq
magic-wormhole
moreutils
mosh
mpv
ncdu
netcat-traditional
org-mode
pwgen
silversearcher-ag
socat
strace
sudo
tree
tmux
vim-nox
"

for p in $PACKAGES; do
	dpkg -s $p > /dev/null || apt install -y $p
done
