#!/bin/sh
set -eu

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" \
            --type string "#000000"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/foreground_color" \
            --type string "#FFFFFF"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_colors" \
            --type boolean "false"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/default_show_menubar" \
            --type boolean "false"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/scrollbar_position" \
            --type string "hidden"

# Mercurial fails if hgrc includes a file that doesn't exist (e.g. ~/.hgrc.local )
# This has been fixed in Mercurial 1.9:
#    "config: ignore include errors for nonexistent files" 
#      -- http://mercurial.selenic.com/wiki/UpgradeNotes
#
# Until Mercurial 1.9 is available in Ubuntu, let's just ensure that file exists.
touch ~/.hgrc.local

# Redirect to /dev/null to prevent "Info: ignoring 'taglist' which is neither removed nor broken"
# from being printed when taglist has already been installed.
vim-addons install taglist > /dev/null
