#!/bin/sh
set -eu

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" \
            --type string "#000000"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/foreground_color" \
            --type string "#FFFFFF"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_colors" \
            --type boolean "false"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/default_show_menubar" \
            --type boolean "false"

gconftool-2 --set "/apps/gnome-terminal/profiles/Default/scrollbar_position" \
            --type string "hidden"
