#!/bin/sh

alias g='git'

setopt extendedglob nomatch notify interactivecomments

unsetopt beep

alias -g 'L'='| less'
alias -g 'G'='| grep'

export FZF_DEFAULT_OPTS="--multi"

# http://nuclearsquid.com/writings/edit-long-commands/
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
