source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

let g:airline#extensions#tabline#enabled = 1

set hlsearch
set ignorecase
set smartcase

set spelllang=en_gb

" After loading a template, move the cursor to <+CURSOR+>:
autocmd User plugin-template-loaded
    \    if search('<+CURSOR+>')
    \  |   execute 'normal! "_da>'
    \  | endif
