(tool-bar-mode -1)
(menu-bar-mode -1)
(setq bookmark-save-flag 1)
(setq make-backup-files nil)
(setq auto-save-default nil)
(icomplete-vertical-mode)
(setq icomplete-show-matches-on-no-input t)
(add-hook 'after-init-hook 'server-start)
(load-theme 'modus-operandi t)

;; Editing
(setq column-number-mode t)
(add-hook 'prog-mode-hook 'eglot-ensure)
(add-hook 'text-mode-hook 'flymake-mode)
(global-diff-hl-mode)
(require 'json-ts-mode)
(require 'go-ts-mode)
(require 'nix-ts-mode)
(add-to-list 'auto-mode-alist '("\\.nix\\'" . nix-ts-mode))
(require 'rust-ts-mode)
(require 'yaml-ts-mode)

;; Shell-ish
(keymap-global-set "C-t" 'shell-pop)
(setq comint-prompt-read-only t)
(add-hook 'eshell-mode-hook 'detached-shell-mode)
(add-hook 'eshell-mode-hook 'fish-completion-mode)
(add-hook 'eshell-mode-hook 'with-editor-export-editor)
(add-hook 'eshell-mode-hook (lambda ()
			      (define-key eshell-mode-map (kbd "C-r") 'consult-history)))
(setq fish-completion-fallback-on-bash-p t)

(load (system-name))
(provide 'init)
